name: Deploy Backend to EC2

on:
  push:
    branches: [ "deploy" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy to EC2 via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            # 1. Asegurar Docker
            sudo apt-get update
            sudo apt-get install -y docker.io docker-compose-v2

            # 2. Carpeta específica para el BACKEND (Diferente a la del frontend)
            rm -rf ~/innovatech-backend-deploy
            git clone https://github.com/${{ github.repository }} ~/innovatech-backend-deploy

            # 3. Entrar y desplegar
            cd ~/innovatech-backend-deploy
            
            # 4. Detener y levantar (Puerto 8081 configurado en tu docker-compose)
            sudo docker compose down || true
            sudo docker compose up -d --build