name: Deploy Backend to EC2

on:
  push:
    branches: [ "deploy" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy to EC2 via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            sudo apt-get update
            sudo apt-get install -y docker.io docker-compose
            # Entrar a la carpeta o clonar si no existe
            if [ ! -d "innovatech-backend" ]; then
              git clone https://github.com/${{ github.repository }} innovatech-backend
            fi
            cd innovatech-backend
            git pull origin deploy
            sudo docker compose up -d --build